[package]
name = "router_library"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]
ic-asset-certification = "3.0.3"
ic-cdk = "0.18.7"
ic-certification = "3.0.3"
ic-http-certification = "3.0.3"
include_dir = { version = "0.7.4", features = ["glob"] }

[features]
default = []
debug-logging = []
